---
title: "Team"
---

We are a small team with expertise in infectious disease modelling, within-host modeling, Bayesian statistics, R-package development, agent-based models, immunology and surveillance systems. We're always happy to hear from potential collaborators or students interested in working with us. Our expertise spans a number of pathogens, including influenza, SARS-CoV-2, RSV, West Nile Virus, Nipah virus and malaria.

- [Ben Hollingdale](https://www.jenner.ac.uk/team/ben-hollingdale) (DPhil student jointly supervised with [Lisa Stockdale](https://www.jenner.ac.uk/team/lisa-stockdale))
- [Bienfait Igiraneza](https://www.psi.ox.ac.uk/our-team/aime-igiraneza) (postdoc)
- [Alexander Greenshields-Watson](https://www.psi.ox.ac.uk/our-team/alexander-greenshields-watson) (postdoc)
- [Punya Alahakoon](https://www.psi.ox.ac.uk/our-team/punya-alahakoon) (postdoc)
- Yan Wang (visiting postdoc)

## Recruitment
### Postdocs
We are not currently hiring postdocs, but please do get in touch with informal enquiries or joint fellowship applications.

### Students
I supervise undergraduate students and MSc students on the [Modelling for Global Health](https://www.ox.ac.uk/admissions/graduate/courses/msc-modelling-for-global-health) course. I am also open to supervising PhD students through the [Clinical Medicine Programme](https://www.ndm.ox.ac.uk/study/graduate-studies) and [Healthcare Data Science CDT](https://www.bdi.ox.ac.uk/study/cdt)